### ISSUE TITLE
Create hook for success callback

### ISSUE THREAD

**Issue by christroutner** [paOol/react-cashid#1]
Correct me if I'm wrong, but in playing with this React component, I didn't see any easy way to hook into a callback function when CashID is successful. I think [this line](https://github.com/paOol/react-cashid/blob/master/src/index.js#L47) is where a hook would go.

The scope of this issue is to add a way for users of the Component to execute a callback function upon successful completion of a CashID challenge. It would probably be a good idea to add a callback hook for error handling as well.

**Comment by paOol** [comment]
added optional callback in v0.2.0
